name: StarCheck
main: StarCheck
authors: RetlocPeck, CodingPenguin
version: 1.0
description: Hypixel Bedwars StarCheck Plugin
commands:
  starcheck:
    usage: /starcheck
    aliases: sc
    description: test